- hosts: all
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: /opt/data
        state: directory
    - name : create secret file
      ansible.builtin.copy:
        dest: /opt/data/secret.txt
        content: TopSecret

 