- name: webserver is installed
  package:
    name: "{{ webserver }}"
    state: present
- name: webserver is running
  service:
    name: "{{ webserver }}"
    state: started
- name: dest folder exists
  file:
    path: "{{ webserver_root_dir }}"
    state: directory