- name: play to create a etc host file
  become: yes
  hosts: all
  tasks:
  - name: dns created
    template:
      src: hosts.j2
      dest: /tmp/hosts
  - name: content appended to existing file
    shell: cat /tmp/hosts >> /etc/hosts
      

    
  