- name: play DRY with loop
  hosts: databases
  become: yes
  tasks:
  - name: mysql and mongo are installed
    package:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - mongodb-org
  - name: mysql and mongo are up
    service:
      name: "{{ item }}"
      state: started
    loop:
    - mysql
    - mongodb-org